"""
Schemas Package
Pydantic请求/响应模型
"""

from app.schemas.common import BaseResponse, PaginatedResponse, ErrorResponse
from app.schemas.auth import (
    LoginRequest,
    LoginResponse,
    RegisterRequest,
    RegisterResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    UserInfo,
)
from app.schemas.agent import (
    AgentBase,
    AgentCreate,
    AgentUpdate,
    AgentDetail,
    AgentListItem,
    AgentStats,
)
from app.schemas.tool import (
    BuiltinToolResponse,
    MCPServerCreate,
    MCPServerUpdate,
    MCPServerResponse,
    MCPServerDetail,
    MCPServerTestResponse,
)
from app.schemas.knowledge import (
    DocumentListResponse,
    DocumentUploadResponse,
    DocumentPreviewResponse,
    QAItem,
    QAListResponse,
    QACreate,
    QAUpdate,
)
from app.schemas.conversation import (
    SessionCreateRequest,
    SessionCreateResponse,
    SessionInfoResponse,
    MessageListResponse,
    ChatMessageRequest,
    ChatStatusResponse,
    FeedbackRequest,
    HistoryListResponse,
    HistoryDetailResponse,
    MessageItem,
    ToolCallItem,
)
from app.schemas.human_service import (
    QueueItem,
    QueueResponse,
    HumanSessionMessagesResponse,
    SendMessageRequest,
    SendMessageResponse,
    QuickReplyItem,
)
from app.schemas.dashboard import (
    MetricsResponse,
    RealtimeStatusResponse,
    IntentDistributionItem,
    IntentDistributionResponse,
    RecentConversationItem,
)
from app.schemas.settings import (
    SettingsResponse,
    SettingsUpdateRequest,
    AvatarUploadResponse,
    PasswordChangeRequest,
    UpdateCheckResponse,
)

__all__ = [
    "BaseResponse",
    "PaginatedResponse",
    "ErrorResponse",
    "LoginRequest",
    "LoginResponse",
    "RegisterRequest",
    "RegisterResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "UserInfo",
    "AgentBase",
    "AgentCreate",
    "AgentUpdate",
    "AgentDetail",
    "AgentListItem",
    "AgentStats",
    "BuiltinToolResponse",
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPServerResponse",
    "MCPServerDetail",
    "MCPServerTestResponse",
    "DocumentListResponse",
    "DocumentUploadResponse",
    "DocumentPreviewResponse",
    "QAItem",
    "QAListResponse",
    "QACreate",
    "QAUpdate",
    "SessionCreateRequest",
    "SessionCreateResponse",
    "SessionInfoResponse",
    "MessageListResponse",
    "ChatMessageRequest",
    "ChatStatusResponse",
    "FeedbackRequest",
    "HistoryListResponse",
    "HistoryDetailResponse",
    "MessageItem",
    "ToolCallItem",
    "QueueItem",
    "QueueResponse",
    "HumanSessionMessagesResponse",
    "SendMessageRequest",
    "SendMessageResponse",
    "QuickReplyItem",
    "MetricsResponse",
    "RealtimeStatusResponse",
    "IntentDistributionItem",
    "IntentDistributionResponse",
    "RecentConversationItem",
    "SettingsResponse",
    "SettingsUpdateRequest",
    "AvatarUploadResponse",
    "PasswordChangeRequest",
    "UpdateCheckResponse",
]
